/**
 * GAME SIMULATION ENGINE (PURE MATH & LOGIC LAYER)
 * 
 * Architectural Role: This file acts as a strict "black box" calculator. 
 * It reads inputs, performs math, and outputs results. It has no awareness 
 * of the DOM, UI elements, or global application state.
 */

/**
 * SECTION 1: CORE DRIVE CALCULATOR
 * 
 * What it does: Simulates a single, isolated offensive possession using your 
 * trusted threshold rules.
 * 
 * Cross-Section Interaction: Resolved via direct property mapping. It doesn't
 * read the entire team object; it only expects two flat numbers (offRating, defRating).
 * This means if your team data structure changes in the future, this math remains unbroken.
 */
export const calculateDriveOutcome = (offRating, defRating, randomRoll) => {
  // Calculates the power balance. A positive score favors the offense, negative favors defense.
  const scoreDiff = offRating - defRating;
  
  // Combines the matchup edge with a bell-curve roll to generate total yardage.
  // Math.max guarantees that even an abysmal drive gains at least 5 yards (no negative yards for simplicity).
  const totalYards = Math.max(5, Math.floor(scoreDiff * 2.5 + 45 + randomRoll));

  let points = 0;
  let isTurnover = 0;

  // Threshold Checks: Evaluates the total yardage against your design rules to assign points.
  if (totalYards >= 75) {
    points = 7;        // Touchdown reached
  } else if (totalYards >= 40) {
    points = 3;        // Settled for a Field Goal
  } else if (randomRoll < -12) {
    isTurnover = 1;    // Extreme negative variance results in a turnover
  }

  // Time of Possession (TOP) Translation:
  // Converts yards gained into a realistic duration of time spent in seconds.
  // Math.max ensures a baseline of 30 seconds is consumed even on an incomplete/stalled sequence.
  const timeUsed = Math.max(30, Math.floor(totalYards * 2.5 + 60));

  // Returns a standardized drive receipt to be processed by the accumulator.
  return { points, yards: totalYards, turnovers: isTurnover, timeUsed };
};

/**
 * SECTION 2: STAT ACCUMULATOR (IMMUTABLE HELPER)
 * 
 * What it does: Combines a single drive's results with the quarter's running totals.
 * 
 * Why it matters: This avoids "state mutation" bugs. Instead of modifying the 
 * existing stats directly, it creates a brand new, updated copy of the stats object.
 */
const accumulateStats = (currentStats, drive) => ({
  points: currentStats.points + drive.points,
  yards: currentStats.yards + drive.yards,
  turnovers: currentStats.turnovers + drive.turnovers,
  top: currentStats.top + drive.timeUsed // Adds raw seconds to the total possession clock
});

/**
 * SECTION 3: MAIN QUARTER ANCHOR
 * 
 * What it does: Manages the 15-minute clock loop and alternates team possessions.
 * 
 * External Dependencies Resolution:
 * 1. Team Ratings: Resolved by passing homeTeam and visitorTeam objects generated by teamFactory.
 * 2. Randomizer: Resolved by passing randomBellCurve as a functional argument from main.js.
 * 
 * How it resolves output back to the app: It returns a completely flat "payload" object. 
 * The controller (main.js) will capture this payload and safely use it to update the scoreboards.
 */
export const simulateQuarter = (visitorTeam, homeTeam, startingPossession, randomBellCurve) => {
  let clock = 900; // Represents a standard 15-minute quarter tracked strictly in seconds (15 * 60)
  let isHomePossession = startingPossession === 'home';
  
  // Initializes blank canvas stat trackers for both teams for this specific quarter
  let visitor = { points: 0, yards: 0, turnovers: 0, top: 0 };
  let home = { points: 0, yards: 0, turnovers: 0, top: 0 };

  // THE TIME LOOP: Keeps running possessions until the 900-second clock is exhausted
  while (clock > 0) {
    // Generates a dynamic random roll for this specific drive using the injected function
    const roll = randomBellCurve(0, 15);

    // Dynamic Engine Route: Feeds the correct off/def ratings into the calculator based on who has the ball
    const drive = isHomePossession 
      ? calculateDriveOutcome(homeTeam.off, visitorTeam.def, roll)
      : calculateDriveOutcome(visitorTeam.off, homeTeam.def, roll);

    // Time Deductor: Subtracts the drive duration from the remaining quarter time
    clock -= drive.timeUsed;

    // Stat Distributor: Routes the drive statistics to the appropriate team's tracking bucket
    if (isHomePossession) {
      home = accumulateStats(home, drive);
    } else {
      visitor = accumulateStats(visitor, drive);
    }

    // Possession Switcher: Alternates the boolean flag so the opposing team takes the ball on the next loop iteration
    isHomePossession = !isHomePossession;
  }

  // RETURN PAYLOAD CONTRACT:
  // Returns a structured, read-only receipt of the entire simulated quarter.
  // NextPossession tells the controller exactly who should receive the ball to start the next quarter.
  return { 
    visitor, 
    home, 
    nextPossession: isHomePossession ? 'home' : 'visitor' 
  };
};